# Generated by Django 5.2.1 on 2025-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cabinet_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requires_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
