# Generated by Django 5.2.1 on 2025-06-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicerequest_requires_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Приостановлена (ожидание замены)'),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина замены'),
        ),
    ]
