# Generated by Django 5.2.1 on 2025-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicerequest_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='replacement_requested',
            field=models.BooleanField(default=False, verbose_name='Запрос на замену оборудования'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requires_replacement',
            field=models.BooleanField(default=False, verbose_name='Требуется замена'),
        ),
    ]
