# Generated by Django 5.2.1 on 2025-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicerequest_replacement_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='new_device_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель нового устройства'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='new_device_serial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер нового устройства'),
        ),
    ]
