# Generated by Django 5.2.1 on 2025-06-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_replacementrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereplacementreport',
            options={},
        ),
    ]
