# Generated by Django 5.2.1 on 2025-06-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_devicereplacementreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereplacementreport',
            options={'verbose_name': 'Перемещение устройства', 'verbose_name_plural': 'Перемещения устройств'},
        ),
        migrations.RemoveField(
            model_name='devicereplacementreport',
            name='new_device_cost',
        ),
        migrations.RemoveField(
            model_name='devicereplacementreport',
            name='new_device_name',
        ),
        migrations.RemoveField(
            model_name='devicereplacementreport',
            name='new_device_serial_number',
        ),
        migrations.RemoveField(
            model_name='devicereplacementreport',
            name='old_device_info',
        ),
        migrations.AddField(
            model_name='devicereplacementreport',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Устройство для перемещения'),
        ),
        migrations.AddField(
            model_name='devicereplacementreport',
            name='from_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_source', to='core.cabinet', verbose_name='Кабинет (источник)'),
        ),
        migrations.AddField(
            model_name='devicereplacementreport',
            name='to_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_target', to='core.cabinet', verbose_name='Кабинет (назначение)'),
        ),
    ]
